export type GroceryStoreBrand = "whole-foods" | "trader-joes";

export type GroceryStoreLocation = {
  id: string;
  brand: GroceryStoreBrand;
  name: string;
  address: string;
  borough: string;
  latitude: number;
  longitude: number;
  sourceUrl: string;
};

export const groceryStoreLocations: GroceryStoreLocation[] = [
  {
    id: "tj-72nd-broadway",
    brand: "trader-joes",
    name: "Trader Joe's 72nd & Broadway",
    address: "2073 Broadway, New York, NY 10023",
    borough: "Manhattan",
    latitude: 40.77895,
    longitude: -73.98258,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/542/",
  },
  {
    id: "tj-chelsea",
    brand: "trader-joes",
    name: "Trader Joe's Chelsea",
    address: "675 6th Ave, New York, NY 10010",
    borough: "Manhattan",
    latitude: 40.74129,
    longitude: -73.99375,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/543/",
  },
  {
    id: "tj-east-village",
    brand: "trader-joes",
    name: "Trader Joe's East Village",
    address: "436 East 14th St, New York, NY 10009",
    borough: "Manhattan",
    latitude: 40.73067,
    longitude: -73.98077,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/546/",
  },
  {
    id: "tj-essex-crossing",
    brand: "trader-joes",
    name: "Trader Joe's Essex Crossing",
    address: "400 Grand St. (Cellar), New York, NY 10002",
    borough: "Manhattan",
    latitude: 40.71567,
    longitude: -73.98611,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/538/",
  },
  {
    id: "tj-harlem",
    brand: "trader-joes",
    name: "Trader Joe's Harlem",
    address: "123 W 125th St, New York, NY 10027",
    borough: "Manhattan",
    latitude: 40.80844,
    longitude: -73.94558,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/576/",
  },
  {
    id: "tj-murray-hill",
    brand: "trader-joes",
    name: "Trader Joe's Murray Hill",
    address: "200 E 32nd St, New York, NY 10016",
    borough: "Manhattan",
    latitude: 40.74447,
    longitude: -73.97915,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/544/",
  },
  {
    id: "tj-soho",
    brand: "trader-joes",
    name: "Trader Joe's SoHo",
    address: "233 Spring Street, New York, NY 10013",
    borough: "Manhattan",
    latitude: 40.72568,
    longitude: -74.00476,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/539/",
  },
  {
    id: "tj-union-square",
    brand: "trader-joes",
    name: "Trader Joe's Union Square",
    address: "142 E 14th St, New York, NY 10003",
    borough: "Manhattan",
    latitude: 40.7341,
    longitude: -73.98853,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/540/",
  },
  {
    id: "tj-bridgemarket",
    brand: "trader-joes",
    name: "Trader Joe's Upper East Side - Bridgemarket",
    address: "405 E. 59th Street, New York, NY 10022",
    borough: "Manhattan",
    latitude: 40.759,
    longitude: -73.95994,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/571/",
  },
  {
    id: "tj-upper-west-side",
    brand: "trader-joes",
    name: "Trader Joe's Upper West Side",
    address: "670 Columbus Ave, New York, NY 10025",
    borough: "Manhattan",
    latitude: 40.79077,
    longitude: -73.96771,
    sourceUrl: "https://locations.traderjoes.com/ny/new-york/545/",
  },
  {
    id: "tj-city-point",
    brand: "trader-joes",
    name: "Trader Joe's Brooklyn - City Point",
    address: "445 Gold St, Brooklyn, NY 11201",
    borough: "Brooklyn",
    latitude: 40.69118,
    longitude: -73.98306,
    sourceUrl: "https://locations.traderjoes.com/ny/brooklyn/547/",
  },
  {
    id: "tj-williamsburg",
    brand: "trader-joes",
    name: "Trader Joe's Brooklyn - Williamsburg",
    address: "200 Kent Ave, Brooklyn, NY 11249",
    borough: "Brooklyn",
    latitude: 40.7177,
    longitude: -73.96465,
    sourceUrl: "https://locations.traderjoes.com/ny/brooklyn/548/",
  },
  {
    id: "tj-court-street",
    brand: "trader-joes",
    name: "Trader Joe's Brooklyn",
    address: "130 Court St, Brooklyn, NY 11201",
    borough: "Brooklyn",
    latitude: 40.69039,
    longitude: -73.99202,
    sourceUrl: "https://locations.traderjoes.com/ny/brooklyn/558/",
  },
  {
    id: "tj-forest-hills",
    brand: "trader-joes",
    name: "Trader Joe's Forest Hills",
    address: "69-65 Yellowstone Blvd, Queens, NY 11375",
    borough: "Queens",
    latitude: 40.72278,
    longitude: -73.84618,
    sourceUrl: "https://locations.traderjoes.com/ny/queens/578/",
  },
  {
    id: "tj-long-island-city",
    brand: "trader-joes",
    name: "Trader Joe's Long Island City",
    address: "22-43 Jackson Ave, Queens, NY 11101",
    borough: "Queens",
    latitude: 40.7453,
    longitude: -73.94531,
    sourceUrl: "https://locations.traderjoes.com/ny/queens/565/",
  },
  {
    id: "tj-rego-park",
    brand: "trader-joes",
    name: "Trader Joe's Rego Park",
    address: "9030 Metropolitan Ave, Queens, NY 11374",
    borough: "Queens",
    latitude: 40.71265,
    longitude: -73.86155,
    sourceUrl: "https://locations.traderjoes.com/ny/queens/557/",
  },
  {
    id: "tj-south-shore",
    brand: "trader-joes",
    name: "Trader Joe's Staten Island - South Shore",
    address: "6400 Amboy Rd, Staten Island, NY 10309",
    borough: "Staten Island",
    latitude: 40.51906,
    longitude: -74.22085,
    sourceUrl: "https://locations.traderjoes.com/ny/staten-island/580/",
  },
  {
    id: "tj-staten-island",
    brand: "trader-joes",
    name: "Trader Joe's Staten Island",
    address: "2385 Richmond Ave, Staten Island, NY 10314",
    borough: "Staten Island",
    latitude: 40.58162,
    longitude: -74.16554,
    sourceUrl: "https://locations.traderjoes.com/ny/staten-island/559/",
  },
  {
    id: "wf-upper-east-side",
    brand: "whole-foods",
    name: "Whole Foods Market Upper East Side",
    address: "1551 3rd Ave, New York, NY 10128",
    borough: "Manhattan",
    latitude: 40.78038,
    longitude: -73.95231,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/uppereastside",
  },
  {
    id: "wf-columbus-circle",
    brand: "whole-foods",
    name: "Whole Foods Market Columbus Circle",
    address: "10 Columbus Cir, Ste Sc101, New York, NY 10019",
    borough: "Manhattan",
    latitude: 40.76847,
    longitude: -73.98273,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/columbuscircle",
  },
  {
    id: "wf-manhattan-west",
    brand: "whole-foods",
    name: "Whole Foods Market Manhattan West",
    address: "450 W 33rd St, New York, NY 10001",
    borough: "Manhattan",
    latitude: 40.75323,
    longitude: -73.99807,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/manhattanwest",
  },
  {
    id: "wf-midtown-east",
    brand: "whole-foods",
    name: "Whole Foods Market Midtown East",
    address: "226 E 57th St, New York, NY 10022",
    borough: "Manhattan",
    latitude: 40.76,
    longitude: -73.96619,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/midtown-east",
  },
  {
    id: "wf-stuytown",
    brand: "whole-foods",
    name: "Whole Foods Market Stuytown",
    address: "409 E 14th St, New York, NY 10009",
    borough: "Manhattan",
    latitude: 40.73171,
    longitude: -73.98279,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/stuytown",
  },
  {
    id: "wf-hells-kitchen",
    brand: "whole-foods",
    name: "Whole Foods Market Hell's Kitchen",
    address: "525 W 52nd St, New York, NY 10019",
    borough: "Manhattan",
    latitude: 40.76665,
    longitude: -73.99194,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/hellskitchen",
  },
  {
    id: "wf-harlem",
    brand: "whole-foods",
    name: "Whole Foods Market Harlem",
    address: "100 W 125th St, New York, NY 10027",
    borough: "Manhattan",
    latitude: 40.80828,
    longitude: -73.94554,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/harlem",
  },
  {
    id: "wf-upper-west-side",
    brand: "whole-foods",
    name: "Whole Foods Market Upper West Side",
    address: "808 Columbus Ave, New York, NY 10025",
    borough: "Manhattan",
    latitude: 40.79536,
    longitude: -73.96543,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/upperwestside",
  },
  {
    id: "wf-nomad",
    brand: "whole-foods",
    name: "Whole Foods Market NoMad",
    address: "63 Madison Ave, New York, NY 10016",
    borough: "Manhattan",
    latitude: 40.74375,
    longitude: -73.98636,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/nomad",
  },
  {
    id: "wf-tribeca",
    brand: "whole-foods",
    name: "Whole Foods Market Tribeca",
    address: "270 Greenwich St, New York, NY 10007",
    borough: "Manhattan",
    latitude: 40.71562,
    longitude: -74.01168,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/tribeca",
  },
  {
    id: "wf-bowery",
    brand: "whole-foods",
    name: "Whole Foods Market Bowery",
    address: "95 East Houston St, New York, NY 10002",
    borough: "Manhattan",
    latitude: 40.72496,
    longitude: -73.99229,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/bowery",
  },
  {
    id: "wf-chelsea",
    brand: "whole-foods",
    name: "Whole Foods Market Chelsea",
    address: "250 7th Ave, New York, NY 10001",
    borough: "Manhattan",
    latitude: 40.74485,
    longitude: -73.99521,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/chelsea",
  },
  {
    id: "wf-union-square",
    brand: "whole-foods",
    name: "Whole Foods Market Union Square",
    address: "4 Union Square S, New York, NY 10003",
    borough: "Manhattan",
    latitude: 40.73591,
    longitude: -73.99108,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/unionsquare",
  },
  {
    id: "wf-one-wall-street",
    brand: "whole-foods",
    name: "Whole Foods Market One Wall Street",
    address: "66 Broadway, New York, NY 10005",
    borough: "Manhattan",
    latitude: 40.70645,
    longitude: -74.01305,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/onewallstreet",
  },
  {
    id: "wf-bryant-park",
    brand: "whole-foods",
    name: "Whole Foods Market Bryant Park",
    address: "1095 6th Ave, New York, NY 10036",
    borough: "Manhattan",
    latitude: 40.7544,
    longitude: -73.9845,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/bryantpark",
  },
  {
    id: "wf-lenox-hill",
    brand: "whole-foods",
    name: "Whole Foods Market Lenox Hill",
    address: "1175 3rd Ave, New York, NY 10065",
    borough: "Manhattan",
    latitude: 40.76783,
    longitude: -73.96294,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/lenoxhill",
  },
  {
    id: "wf-brooklyn-third-street",
    brand: "whole-foods",
    name: "Whole Foods Market Brooklyn",
    address: "214 3rd St, Brooklyn, NY 11215",
    borough: "Brooklyn",
    latitude: 40.67494,
    longitude: -73.98764,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/thirdand3rd",
  },
  {
    id: "wf-williamsburg",
    brand: "whole-foods",
    name: "Whole Foods Market Williamsburg",
    address: "238 Bedford Ave, Brooklyn, NY 11249",
    borough: "Brooklyn",
    latitude: 40.7167,
    longitude: -73.95962,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/williamsburg",
  },
  {
    id: "wf-fort-greene",
    brand: "whole-foods",
    name: "Whole Foods Market Fort Greene",
    address: "292 Ashland Pl, Brooklyn, NY 11217",
    borough: "Brooklyn",
    latitude: 40.68668,
    longitude: -73.97788,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/fortgreene",
  },
  {
    id: "wf-industry-city",
    brand: "whole-foods",
    name: "Whole Foods Market Industry City",
    address: "167 41st St, Brooklyn, NY 11232",
    borough: "Brooklyn",
    latitude: 40.6551,
    longitude: -74.00628,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/industrycity",
  },
  {
    id: "wf-grand-street",
    brand: "whole-foods",
    name: "Whole Foods Market Grand Street",
    address: "774 Grand Street, Brooklyn, NY 11211",
    borough: "Brooklyn",
    latitude: 40.71129,
    longitude: -73.94401,
    sourceUrl: "https://www.wholefoodsmarket.com/stores/grandstreet",
  },
];
